package by.mrf1n.finance.currencycom.model.enums;

public enum RejectReason {

  ACCOUNT_NOT_FOUND,
  CLOSED_MARKET,
  CLOSE_ONLY,
  ENGINE_BUSY,
  HEDGING_MODE_GSL,
  INSTRUMENT_NOT_AVAILABLE,
  INSTRUMENT_NOT_FOUND,
  INVALID_ORDER,
  INVALID_ORDER_QTY,
  INVALID_PRICE,
  LONG_ONLY,
  OFF_MARKET,
  ORDER_NOT_FOUND,
  ORIGINAL_GSL_UPDATE,
  POSITION_NOT_FOUND,
  RC_INSTRUMENT_CLIENT_MOP,
  RC_INSTRUMENT_GLOBAL_MOP,
  RC_NOT_ENOUGH_MARGIN,
  RC_NOT_FOUND,
  RC_NO_RATES,
  RC_SETTLEMENT,
  RC_UNKNOWN,
  REQUIRED_GSL,
  RISK_CHECK,
  THROTTLING,
  UNKNOWN

}
